services:
  - type: web
    name: teacher-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node teacher.js'
    envVars:
      - key: PORT
        value: "10001"
      - key: DATABASE_UR
        value: "postgresql://root:5LwG3ddvMUxytEwxP2cLpoWpbCBwicvE@dpg-cpitueuct0pc738154gg-a/attendence_unym"

  - type: web
    name: qr-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: PORT
        value: "10000"

  - type: web
    name: home-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node home.js'
    envVars:
      - key: TEACHER_PORT
        value: "10001"
      - key: QR_PORT
        value: "10000"
      - key: PORT
        value: "10002"
    routes:
      - name: home
        paths:
          - "/*"

      - name: teacher-dashboard
        paths:
          - "/teacher-dashboard"
